baseURL = "https://vinibaggio.net/"
languageCode = "en-us"
title = "vinibaggio.net"
theme = "vb-nuo"
enableRobotsTXT = true
PygmentsCodeFences = true
canonifyurls = true

[imaging]
quality = 100

# Disqus Username
# disqusShortname = "disqus_shortname"

# Google Analytics UA number
googleAnalytics = "UA-6968963-1"

# Copyright of your post
copyright = "© This post is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License, please refer the original work if you wish to quote or reproduce. Contact me if you want to use this content commercially."

# Initial site menu, you can extend menu with content.
[[menu.main]]
  name = "Updates"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "My book (in 🇧🇷)"
  weight = 11
  identifier = "mybook"
  url = "https://www.casadocodigo.com.br/products/livro-ruby-on-rails"

# Add your own params here
[params]
  author = "Vinicius Baggio Fuentes"
  seotitle = "vinibaggio.net"
  subtitle = "vinibaggio's blog"
  description = "Vinicius Baggio Fuentes space on the internet. I share my words and other productions here, such as photos and code."
  paginate = 10

  # Choose your social networks
  email = "vinibaggio@gmail.com"
  github = "vinibaggio"
  twitter = "vinibaggio"
  linkedin = "vinibaggio"
  # weibo = "weibo_username"
  # wechat= "/img/qrcode.jpg" # Replace with your wechat qrcode image
  # facebook = "facebook_username"
  # google = "googlplus_id_number"
  instagram = "vinibaggio"
  # youtube = "vinibaggio"
  # vimeo = "vimeo_username"
  medium = "v"
  # quora = "quora_username"
  # pinterest = "pinterest_username"
  # dribbble = "dribbble_username"
  # behance = "behance_username"
  # jsfiddle = "jsfiddle_username"
  # codepen = "codepen_username"
  # zhihu = "zhihu_username"
  # douban = "douban_username"
  # bilibili = "bilibili_id_number"

  # Changyan Comments (China Only)
  # changyan = false
  # changyanId = "cyt3toRiB"
  # changyanConf = "prod_0908b1cb9a581501753cce1ed074dbe3"

  # Google Webmaster
  # https://www.google.com/webmasters/
  # googleSiteVerification = "_moDmnnBNVLBN1rzNxyGUGdPHE20YgbmrtzLIbxaWFc"

  # Bing Webmaster
  # https://www.bing.com/toolbox/webmaster/
  # msValidate = "22596E34341DD1D17D6022C44647E587"

  # Baidu Webmaster (China Only)
  # https://zhanzhang.baidu.com/
  # baiduSiteVerification = "MZ23SPxxfa"

  # Sogou Webmaster (China Only)
  # http://zhanzhang.sogou.com/
  # sogouSiteVerification = "m2jktMQTZm"

  # 360 Webmaster (China Only)
  # http://zhanzhang.so.com/
  # soSiteVerification = "b7ab3b4c2edbc856642004d1b8c27a91"

  # Baidu Tongji (China Only)
  # https://tongji.baidu.com/
  # baiduTongji = "e21dc1e8a592188271b615159dc88af7"

  # ICP Number (China Only)
  # ICP = "苏ICP备16005986号-2"
